# Generated by Django 4.2 on 2023-04-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_alter_profile_avatar'),
        ('forum', '0002_alter_post_options_alter_theme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.profile'),
        ),
    ]
