# Generated by Django 4.2 on 2023-04-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(default='static/images/profile.png', upload_to='static/images')),
                ('telegram', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'verbose_name': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='User_Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='enter.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='enter.profile')),
            ],
            options={
                'verbose_name': 'User_Reputations',
            },
        ),
    ]
