# Generated by Django 4.2 on 2023-04-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user_reputation',
            options={},
        ),
    ]
