# Generated by Django 4.2 on 2023-04-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0006_alter_profile_user'),
        ('enter', '0008_alter_profile_avatar'),
    ]

    operations = [
    ]
