# Generated by Django 4.2 on 2023-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='static/image/cv.png', upload_to='static/images'),
        ),
    ]
