# Generated by Django 4.2 on 2023-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0003_alter_skill_options_alter_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='media/image/cv.png', upload_to='static/images'),
        ),
    ]
