# Generated by Django 4.2 on 2023-04-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0006_alter_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='static/image/cv.png', upload_to='static/images'),
        ),
    ]
