# Generated by Django 4.2 on 2023-04-30 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0009_merge_20230430_0227'),
        ('hunter', '0007_alter_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.profile'),
        ),
    ]
