# Generated by Django 4.2 on 2023-04-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_theme_author'),
        ('hunter', '0008_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.theme'),
        ),
    ]
