# Generated by Django 4.2 on 2023-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0009_project_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(blank=True, to='hunter.role'),
        ),
    ]
